---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-deploy
  labels:
    app: facebook
    env: lab
spec:
  selector:
    matchLabels:
      app: facebook
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
      
  template:
    metadata:
      name: fb-pod
      labels:
        app: facebook
        env: lab
        version: V1_AC
    spec:
      containers:
        - name: fb-container
          image: sravani2310/mcapp:latest
    
