---
apiVersion: v1
kind: Service
metadata:
  name: fb-lb-svc
  labels:
    app: facebook
spec:
  type: LoadBalancer
  ports:
    - port: 83
      targetPort: 8080
      protocol: TCP
  selector:
    app: facebook
